### ISSUE TITLE
private method `open' called for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by rennhak** [joshed-io/aud#1]
Hi there,

just want to give you a heads up, that `aud` fails on my local system here with the following error:

```
% aud            
/home/br/.rvm/gems/ruby-2.0.0-p353/gems/unimidi-0.3.3-x86-linux/lib/unimidi/congruous_api_adapter.rb:147:in `use_device': private method `open' called for nil:NilClass (NoMethodError)
        from /home/br/.rvm/gems/ruby-2.0.0-p353/gems/unimidi-0.3.3-x86-linux/lib/unimidi/congruous_api_adapter.rb:78:in `first'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/gems/aud-0.0.3/lib/aud/cli.rb:58:in `listen'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/gems/aud-0.0.3/bin/aud:6:in `<top (required)>'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/bin/aud:23:in `load'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/bin/aud:23:in `<main>'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
        from /home/br/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'`

```

**Comment by joshed-io** [comment]
This is probably because your system doesn't have a MIDI device configured.  The [UNIMidi gem](https://github.com/arirusso/unimidi) has instructions on how to setup a MIDI device. Let me know if that helps.

Still, the error message should be much better. Will improve that under this issue.

**Comment by rennhak** [comment]
No luck here, but thanks for the tip.
